### PR TITLE
add reset status for upstreamRequest and corresponding check code at …

### PR DESCRIPTION
**Pull request by neverhook**
…the beginning of appendHeader/Data/Trailer method; fix rpc_test typo

### CODE REVIEW

**Comment by neverhook** [comment]
FIX #162

**Comment by neverhook** [comment]
golint & goimports result :

image

**Comment by ldxdl** [comment]
Pls provide more details about cases that upstreamProcessDone dont cover and see if we can reuse it to resolve the problem

**Comment by nejisama** [comment]
close #162

**Pull request merged**
