### PR TITLE
fix: #181 Data race

### PR DESCRIPTION
**Pull request by dawxy**
fix:#181

### CODE REVIEW

**Comment by ldxdl** [comment]
Because the code you changed is pretty important, pls provide more details about your the correctness of your code change, including :
+ unit test result
+ integration test result
+ fuzzy test result
+ goimports/golint results

**Comment by dawxy** [comment]
@ldxdl  
Can't we use "go test -race" in unit tests? 
I see some other DATA RACE warnings.

**Comment by ldxdl** [comment]
Good point, @nejisama pls pay attention on race detection in test phase, and check and fix it in 0.2.0 testing.

**Comment by dawxy** [comment]
Then I cancel the -race parameter first, then only add the unit test, because I don't know how to add the integration test and fuzzy test.

**Pull request merged**
